import { useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import {
  addPictureTags,
  getAdminPicture,
  listPictureTags,
  listReviews,
  removePictureTag,
  reviewPicture,
  type AdminPictureSummary,
  type ModerationRecord,
  type PictureTag,
} from '@/api/pictures'
import { listTags, type TagInfo } from '@/api/tags'
import { Button } from '@/react-app/ui/shadcn/button'
import { Input } from '@/react-app/ui/shadcn/input'
import { Textarea } from '@/react-app/ui/shadcn/textarea'
import { formatBytes } from '@/utils/format'

function ReviewStatusBadge({ status }: { status: string }) {
  const cfg: Record<string, { bg: string; color: string }> = {
    APPROVED: { bg: 'rgba(31,138,112,0.14)', color: '#116350' },
    REJECTED: { bg: 'rgba(154,52,18,0.12)', color: '#9a3412' },
    PENDING: { bg: 'rgba(138,92,0,0.12)', color: '#8a5c00' },
  }
  const s = cfg[status] ?? { bg: 'rgba(90,82,76,0.1)', color: '#5a524c' }
  return (
    <span style={{ ...s, padding: '4px 12px', borderRadius: 999, fontSize: '0.78rem', fontWeight: 700 }}>
      {status}
    </span>
  )
}

export default function AdminReviewDetailPage() {
  const params = useParams()
  const navigate = useNavigate()
  const pictureId = String(params.id || '')

  const [detail, setDetail] = useState<AdminPictureSummary | null>(null)
  const [history, setHistory] = useState<ModerationRecord[]>([])
  const [loading, setLoading] = useState(false)
  const [reviewing, setReviewing] = useState(false)
  const [reviewSuccess, setReviewSuccess] = useState<string | null>(null)
  const [reviewError, setReviewError] = useState<string | null>(null)

  const [tags, setTags] = useState<PictureTag[]>([])
  const [tagsLoading, setTagsLoading] = useState(false)
  const [tagInput, setTagInput] = useState('')
  const [addingTag, setAddingTag] = useState(false)
  const [selectedTagName, setSelectedTagName] = useState('')
  const [tagSuggestions, setTagSuggestions] = useState<TagInfo[]>([])
  const [showSuggestions, setShowSuggestions] = useState(false)

  const [reviewStatus, setReviewStatus] = useState<'APPROVED' | 'REJECTED'>('APPROVED')
  const [reviewReason, setReviewReason] = useState('')

  const loadDetail = async () => {
    // Try cached first for speed
    const cached = sessionStorage.getItem('cpp:admin:selected')
    if (cached) {
      try {
        const parsed = JSON.parse(cached) as AdminPictureSummary
        if (parsed?.id === pictureId) setDetail(parsed)
      } catch { /* ignore */ }
    }
    try {
      const data = await getAdminPicture(pictureId)
      setDetail(data)
    } catch { /* keep cached */ }
  }

  const loadTags = async () => {
    setTagsLoading(true)
    try {
      const data = await listPictureTags(pictureId)
      setTags(data)
    } finally {
      setTagsLoading(false)
    }
  }

  const loadHistory = async () => {
    setLoading(true)
    try {
      const data = await listReviews(pictureId, { page: 0, size: 20, sortBy: 'reviewedAt', sortDir: 'desc' })
      setHistory(data.items)
    } finally {
      setLoading(false)
    }
  }

  const fetchTagSuggestions = async (keyword: string) => {
    const trimmed = keyword.trim()
    if (!trimmed) { setTagSuggestions([]); setShowSuggestions(false); return }
    try {
      const data = await listTags({ page: 0, size: 8, keyword: trimmed })
      setTagSuggestions(data.items)
      setShowSuggestions(true)
    } catch { setTagSuggestions([]); setShowSuggestions(false) }
  }

  const handleTagSelect = (tagName: string) => {
    setTagInput(tagName)
    setSelectedTagName(tagName)
    setShowSuggestions(false)
  }

  const addTag = async () => {
    const value = tagInput.trim()
    if (!value) return
    setAddingTag(true)
    try {
      const newTags = await addPictureTags(pictureId, {
        tags: [{ text: value }],
        provider: 'admin',
        autoGenerated: false,
      })
      setTags(newTags)
      setTagInput('')
      setSelectedTagName('')
    } finally {
      setAddingTag(false)
    }
  }

  const removeTag = async (tag: PictureTag) => {
    try {
      await removePictureTag(pictureId, tag.id)
      setTags(tags.filter((item) => item.id !== tag.id))
    } catch { /* ignore */ }
  }

  const submitReview = async () => {
    setReviewing(true)
    setReviewSuccess(null)
    setReviewError(null)
    try {
      await reviewPicture(pictureId, { status: reviewStatus, reason: reviewReason || undefined })
      setReviewReason('')
      setReviewSuccess(`Picture ${reviewStatus.toLowerCase()} successfully.`)
      await Promise.all([loadHistory(), loadDetail()])
    } catch {
      setReviewError('Review submission failed. Please try again.')
    } finally {
      setReviewing(false)
    }
  }

  useEffect(() => {
    void Promise.all([loadDetail(), loadTags(), loadHistory()])
  }, [pictureId]) // eslint-disable-line react-hooks/exhaustive-deps

  useEffect(() => {
    const timeout = setTimeout(() => {
      if (tagInput !== selectedTagName) void fetchTagSuggestions(tagInput)
    }, 300)
    return () => clearTimeout(timeout)
  }, [tagInput, selectedTagName])

  return (
    <div className="page">
      <div className="page-header">
        <div>
          <button
            onClick={() => navigate('/admin/reviews')}
            style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--ink-soft)', fontSize: '0.85rem', marginBottom: 8, padding: 0 }}
          >
            ← Back to Queue
          </button>
          <h1 className="page-title">Review Detail</h1>
          {detail && <p className="page-subtitle">{detail.name}</p>}
        </div>
      </div>

      <div className="responsive-two-col" style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(360px, 1fr))', gap: 20 }}>
        {/* Left — Asset panel */}
        <section className="panel">
          <h2 style={{ margin: '0 0 16px', fontSize: '1rem', textTransform: 'uppercase', letterSpacing: '0.08em', color: 'var(--ink-soft)', fontWeight: 700 }}>
            Asset Preview
          </h2>
          {detail ? (
            <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
              <div style={{ borderRadius: 18, overflow: 'hidden', aspectRatio: '4/3', background: '#efe7dd' }}>
                <img src={detail.url} alt={detail.name} style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
              </div>

              {/* Metadata chips */}
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8 }}>
                {[
                  { label: 'Size', value: formatBytes(detail.sizeBytes) },
                  { label: 'Resolution', value: detail.width ? `${detail.width}×${detail.height}` : '—' },
                  { label: 'Owner', value: detail.ownerDisplayName || detail.ownerUsername || '—' },
                  { label: 'Status', value: detail.reviewStatus },
                ].map(({ label, value }) => (
                  <div key={label} style={{ padding: '10px 14px', borderRadius: 12, background: 'var(--bg-elevated)', border: '1px solid var(--stroke-soft)' }}>
                    <div style={{ fontSize: '0.7rem', textTransform: 'uppercase', letterSpacing: '0.08em', color: 'var(--ink-soft)', fontWeight: 700 }}>{label}</div>
                    <div style={{ fontWeight: 700, fontSize: '0.9rem', marginTop: 2 }}>{value}</div>
                  </div>
                ))}
              </div>

              {/* Tags */}
              <div>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 }}>
                  <div style={{ fontSize: '0.78rem', textTransform: 'uppercase', letterSpacing: '0.08em', color: 'var(--ink-soft)', fontWeight: 700 }}>
                    Tags ({tags.length})
                  </div>
                </div>

                <div style={{ position: 'relative', marginBottom: 10 }}>
                  <div style={{ display: 'flex', gap: 8 }}>
                    <div style={{ position: 'relative', flex: 1 }}>
                      <Input
                        value={tagInput}
                        onChange={(e) => { setTagInput(e.target.value); setSelectedTagName(e.target.value) }}
                        placeholder="Add a tag…"
                        onKeyDown={(e) => e.key === 'Enter' && void addTag()}
                      />
                      {showSuggestions && tagSuggestions.length > 0 && (
                        <div style={{
                          position: 'absolute', top: '100%', left: 0, right: 0,
                          background: 'var(--bg-surface)', border: '1px solid var(--stroke-soft)',
                          borderRadius: 10, marginTop: 4, zIndex: 20,
                          boxShadow: '0 8px 24px rgba(30,20,10,0.1)', maxHeight: 180, overflowY: 'auto',
                        }}>
                          {tagSuggestions.map((tag) => (
                            <div
                              key={tag.id}
                              onMouseDown={() => handleTagSelect(tag.name)}
                              style={{ padding: '8px 14px', cursor: 'pointer', fontSize: '0.88rem', borderBottom: '1px solid var(--stroke-soft)' }}
                            >
                              {tag.name}
                            </div>
                          ))}
                        </div>
                      )}
                    </div>
                    <Button variant="primary" onClick={() => void addTag()} disabled={addingTag}>
                      {addingTag ? '…' : 'Add'}
                    </Button>
                  </div>
                </div>

                {tagsLoading ? (
                  <div style={{ fontSize: '0.85em', color: 'var(--ink-soft)' }}>Loading tags…</div>
                ) : (
                  <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
                    {tags.map((tag) => (
                      <span
                        key={tag.id}
                        style={{
                          display: 'inline-flex', alignItems: 'center', gap: 6,
                          padding: '5px 10px', borderRadius: 999, fontSize: '0.8rem', fontWeight: 600,
                          background: tag.autoGenerated ? 'rgba(100,116,139,0.1)' : 'rgba(31,138,112,0.12)',
                          color: tag.autoGenerated ? '#475569' : '#116350',
                        }}
                      >
                        {tag.tagText}
                        {tag.confidenceScore != null && (
                          <span style={{ opacity: 0.6, fontSize: '0.7rem' }}>
                            {(tag.confidenceScore * 100).toFixed(0)}%
                          </span>
                        )}
                        <button
                          onClick={() => void removeTag(tag)}
                          aria-label={`Remove tag ${tag.tagText}`}
                          style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'inherit', fontSize: '1rem', lineHeight: 1, padding: 0 }}
                        >
                          ×
                        </button>
                      </span>
                    ))}
                    {tags.length === 0 && <span style={{ fontSize: '0.82rem', color: 'var(--ink-soft)' }}>No tags yet.</span>}
                  </div>
                )}
              </div>
            </div>
          ) : (
            <div style={{ padding: 32, textAlign: 'center', color: 'var(--ink-soft)' }}>
              Loading asset…
            </div>
          )}
        </section>

        {/* Right — Decision panel */}
        <div style={{ display: 'grid', gap: 20, alignContent: 'start' }}>
          <section className="panel soft">
            <h2 style={{ margin: '0 0 16px', fontSize: '1rem', textTransform: 'uppercase', letterSpacing: '0.08em', color: 'var(--ink-soft)', fontWeight: 700 }}>
              Decision
            </h2>

            {/* Decision buttons */}
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10, marginBottom: 16 }}>
              {(['APPROVED', 'REJECTED'] as const).map((status) => (
                <button
                  key={status}
                  onClick={() => setReviewStatus(status)}
                  style={{
                    padding: '14px 16px',
                    borderRadius: 14,
                    border: `2px solid ${reviewStatus === status
                      ? (status === 'APPROVED' ? 'rgba(31,138,112,0.6)' : 'rgba(154,52,18,0.6)')
                      : 'var(--stroke-soft)'}`,
                    background: reviewStatus === status
                      ? (status === 'APPROVED' ? 'rgba(31,138,112,0.1)' : 'rgba(154,52,18,0.08)')
                      : 'transparent',
                    cursor: 'pointer',
                    fontWeight: 700,
                    fontSize: '0.9rem',
                    color: reviewStatus === status
                      ? (status === 'APPROVED' ? '#116350' : '#9a3412')
                      : 'var(--ink-soft)',
                    transition: 'all 0.15s ease',
                  }}
                >
                  {status === 'APPROVED' ? '✓ Approve' : '✕ Reject'}
                </button>
              ))}
            </div>

            {/* Reason */}
            <label className="field" style={{ marginBottom: 16 }}>
              <span className="label">Reason {reviewStatus === 'REJECTED' ? '(recommended)' : '(optional)'}</span>
              <Textarea
                value={reviewReason}
                onChange={(e) => setReviewReason(e.target.value)}
                placeholder={reviewStatus === 'REJECTED' ? 'Explain why this was rejected…' : 'Add notes (optional)'}
                rows={3}
              />
            </label>

            {reviewSuccess && (
              <div style={{ padding: '10px 14px', borderRadius: 10, background: 'rgba(31,138,112,0.12)', color: '#116350', fontWeight: 600, fontSize: '0.88rem', marginBottom: 12 }}>
                ✓ {reviewSuccess}
              </div>
            )}
            {reviewError && (
              <div className="form-error" style={{ marginBottom: 12 }}>{reviewError}</div>
            )}

            <Button
              variant="primary"
              onClick={() => void submitReview()}
              disabled={reviewing}
              style={{ width: '100%', height: 44 }}
            >
              {reviewing ? 'Submitting…' : `Submit — ${reviewStatus === 'APPROVED' ? 'Approve' : 'Reject'}`}
            </Button>
          </section>

          {/* Moderation history */}
          <section className="panel">
            <h2 style={{ margin: '0 0 16px', fontSize: '1rem', textTransform: 'uppercase', letterSpacing: '0.08em', color: 'var(--ink-soft)', fontWeight: 700 }}>
              Review History
            </h2>
            {loading ? (
              <div style={{ color: 'var(--ink-soft)', fontSize: '0.85rem' }}>Loading…</div>
            ) : history.length === 0 ? (
              <div style={{ padding: '16px 0', textAlign: 'center', color: 'var(--ink-soft)', fontSize: '0.88rem' }}>
                No review history yet.
              </div>
            ) : (
              <div style={{ display: 'grid', gap: 12 }}>
                {history.map((item) => (
                  <div
                    key={item.id}
                    style={{
                      padding: '12px 14px',
                      borderLeft: `3px solid ${item.toStatus === 'APPROVED' ? 'rgba(31,138,112,0.5)' : item.toStatus === 'REJECTED' ? 'rgba(154,52,18,0.5)' : 'var(--stroke-soft)'}`,
                      background: 'var(--bg-elevated)',
                      borderRadius: '0 10px 10px 0',
                    }}
                  >
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 4 }}>
                      <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
                        <ReviewStatusBadge status={item.fromStatus} />
                        <span style={{ color: 'var(--ink-soft)', fontSize: '0.78rem' }}>→</span>
                        <ReviewStatusBadge status={item.toStatus} />
                      </div>
                      <span style={{ fontSize: '0.72rem', color: 'var(--ink-soft)' }}>
                        {new Date(item.reviewedAt).toLocaleString()}
                      </span>
                    </div>
                    <div style={{ fontSize: '0.82rem', color: 'var(--ink-soft)', marginBottom: item.reason ? 4 : 0 }}>
                      by {item.reviewerDisplayName || item.reviewerUsername || item.reviewerId}
                    </div>
                    {item.reason && (
                      <div style={{ fontStyle: 'italic', fontSize: '0.82rem', color: 'var(--ink-soft)' }}>
                        "{item.reason}"
                      </div>
                    )}
                  </div>
                ))}
              </div>
            )}
          </section>
        </div>
      </div>
    </div>
  )
}

