import { useEffect, useState } from 'react'
import { useParams } from 'react-router-dom'
import {
  addPictureTags,
  getAdminPicture,
  listPictureTags,
  listReviews,
  removePictureTag,
  reviewPicture,
  type AdminPictureSummary,
  type ModerationRecord,
  type PictureTag,
} from '@/api/pictures'
import { listTags, type TagInfo } from '@/api/tags'
import PageShell from './common/PageShell'
import { Button } from '@/react-app/ui/shadcn/button'
import { Input } from '@/react-app/ui/shadcn/input'
import { Textarea } from '@/react-app/ui/shadcn/textarea'

export default function AdminReviewDetailPage() {
  const params = useParams()
  const pictureId = String(params.id || '')

  const [detail, setDetail] = useState<AdminPictureSummary | null>(null)
  const [history, setHistory] = useState<ModerationRecord[]>([])
  const [loading, setLoading] = useState(false)
  const [reviewing, setReviewing] = useState(false)
  const [tags, setTags] = useState<PictureTag[]>([])
  const [tagsLoading, setTagsLoading] = useState(false)
  const [tagInput, setTagInput] = useState('')
  const [addingTag, setAddingTag] = useState(false)
  const [selectedTagName, setSelectedTagName] = useState('')
  const [tagSuggestions, setTagSuggestions] = useState<TagInfo[]>([])
  const [showSuggestions, setShowSuggestions] = useState(false)

  const [reviewStatus, setReviewStatus] = useState<'APPROVED' | 'REJECTED'>('APPROVED')
  const [reviewReason, setReviewReason] = useState('')

  const loadDetail = async () => {
    const cached = sessionStorage.getItem('cpp:admin:selected')
    if (cached) {
      try {
        const parsed = JSON.parse(cached) as AdminPictureSummary
        if (parsed?.id === pictureId) {
          setDetail(parsed)
        }
      } catch {
        setDetail(null)
      }
    }
    try {
      const data = await getAdminPicture(pictureId)
      setDetail(data)
    } catch {
      // Keep cached detail if available
    }
  }

  const loadTags = async () => {
    setTagsLoading(true)
    try {
      const data = await listPictureTags(pictureId)
      setTags(data)
    } catch (error) {
      console.error('Failed to load tags', error)
    } finally {
      setTagsLoading(false)
    }
  }

  const loadHistory = async () => {
    setLoading(true)
    try {
      const data = await listReviews(pictureId, {
        page: 0,
        size: 20,
        sortBy: 'reviewedAt',
        sortDir: 'desc',
      })
      setHistory(data.items)
    } catch (error) {
      console.error('Failed to load review history', error)
    } finally {
      setLoading(false)
    }
  }

  const fetchTagSuggestions = async (keyword: string) => {
    const trimmed = keyword.trim()
    if (!trimmed) {
      setTagSuggestions([])
      setShowSuggestions(false)
      return
    }
    try {
      const data = await listTags({ page: 0, size: 8, keyword: trimmed })
      setTagSuggestions(data.items)
      setShowSuggestions(true)
    } catch {
      setTagSuggestions([])
      setShowSuggestions(false)
    }
  }

  const handleTagSelect = (tagName: string) => {
    setTagInput(tagName)
    setSelectedTagName(tagName)
    setShowSuggestions(false)
  }

  const addTag = async () => {
    const value = tagInput.trim()
    if (!value) return
    setAddingTag(true)
    try {
      const newTags = await addPictureTags(pictureId, {
        tags: [{ text: value }],
        provider: 'manual',
        autoGenerated: false,
      })
      setTags(newTags)
      setTagInput('')
      setSelectedTagName('')
    } catch (error) {
      console.error('Failed to add tag', error)
    } finally {
      setAddingTag(false)
    }
  }

  const removeTag = async (tag: PictureTag) => {
    try {
      await removePictureTag(pictureId, tag.id)
      setTags(tags.filter((item) => item.id !== tag.id))
    } catch (error) {
      console.error('Failed to remove tag', error)
    }
  }

  const submitReview = async () => {
    setReviewing(true)
    try {
      await reviewPicture(pictureId, {
        status: reviewStatus,
        reason: reviewReason || undefined,
      })
      setReviewReason('')
      await loadHistory()
    } catch (error) {
      console.error('Review failed', error)
    } finally {
      setReviewing(false)
    }
  }

  useEffect(() => {
    loadDetail()
    loadTags()
    loadHistory()
  }, [pictureId]) // eslint-disable-line react-hooks/exhaustive-deps

  useEffect(() => {
    const timeout = setTimeout(() => {
      if (tagInput !== selectedTagName) {
        fetchTagSuggestions(tagInput)
      }
    }, 300)
    return () => clearTimeout(timeout)
  }, [tagInput, selectedTagName])

  function formatBytes(bytes: number): string {
    if (bytes === 0) return '0 B'
    const k = 1024
    const sizes = ['B', 'KB', 'MB', 'GB']
    const i = Math.floor(Math.log(bytes) / Math.log(k))
    return `${parseFloat((bytes / Math.pow(k, i)).toFixed(2))} ${sizes[i]}`
  }

  return (
    <PageShell title="Review Detail">
      <div style={{ display: 'grid', gap: 24 }}>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(400px, 1fr))', gap: 16 }}>
          {/* Asset Panel */}
          <section className="panel">
            <h2 style={{ margin: '0 0 16px', fontSize: '1.1rem' }}>Asset</h2>
            {detail ? (
              <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
                <div
                  style={{
                    width: '100%',
                    borderRadius: 18,
                    overflow: 'hidden',
                    aspectRatio: '4 / 3',
                    background: '#efe7dd',
                  }}
                >
                  <img src={detail.url} alt={detail.name} style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
                </div>
                <div>
                  <h3 style={{ margin: '0 0 12px' }}>{detail.name}</h3>
                  <div style={{ display: 'flex', justifyContent: 'space-between', color: 'var(--ink-soft)', marginBottom: 8 }}>
                    <span>Owner</span>
                    <strong style={{ color: 'var(--ink-strong)' }}>{detail.ownerDisplayName || detail.ownerUsername || '--'}</strong>
                  </div>
                  <div style={{ display: 'flex', justifyContent: 'space-between', color: 'var(--ink-soft)', marginBottom: 8 }}>
                    <span>Size</span>
                    <strong style={{ color: 'var(--ink-strong)' }}>{formatBytes(detail.sizeBytes)}</strong>
                  </div>
                  <div style={{ display: 'flex', justifyContent: 'space-between', color: 'var(--ink-soft)' }}>
                    <span>Resolution</span>
                    <strong style={{ color: 'var(--ink-strong)' }}>
                      {detail.width || '--'} x {detail.height || '--'}
                    </strong>
                  </div>
                </div>

                {/* Tags Section */}
                <div style={{ display: 'grid', gap: 10 }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                    <strong>Tags</strong>
                    <span style={{ fontSize: '0.85em', color: 'var(--ink-soft)' }}>{tags.length} total</span>
                  </div>
                  <div style={{ display: 'flex', gap: 10, alignItems: 'center', flexWrap: 'wrap', position: 'relative' }}>
                    <div style={{ position: 'relative', flex: 1, minWidth: 200 }}>
                      <Input
                        value={tagInput}
                        onChange={(e) => {
                          setTagInput(e.target.value)
                          setSelectedTagName(e.target.value)
                        }}
                        placeholder="Add a tag"
                        onKeyDown={(e) => e.key === 'Enter' && addTag()}
                      />
                      {showSuggestions && tagSuggestions.length > 0 && (
                        <div
                          style={{
                            position: 'absolute',
                            top: '100%',
                            left: 0,
                            right: 0,
                            background: 'var(--bg)',
                            border: '1px solid var(--border)',
                            borderRadius: 8,
                            marginTop: 4,
                            zIndex: 10,
                            maxHeight: 200,
                            overflowY: 'auto',
                          }}
                        >
                          {tagSuggestions.map((tag) => (
                            <div
                              key={tag.id}
                              style={{
                                padding: '8px 12px',
                                cursor: 'pointer',
                                borderBottom: '1px solid var(--border)',
                              }}
                              onMouseDown={() => handleTagSelect(tag.name)}
                            >
                              {tag.name}
                            </div>
                          ))}
                        </div>
                      )}
                    </div>
                    <Button variant="primary" onClick={() => void addTag()} disabled={addingTag}>
                      {addingTag ? 'Adding...' : 'Add'}
                    </Button>
                  </div>
                  {tagsLoading ? (
                    <div style={{ fontSize: '0.85em', color: 'var(--ink-soft)' }}>Loading tags...</div>
                  ) : (
                    <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
                      {tags.map((tagItem) => (
                        <span
                          key={tagItem.id}
                          className="tag"
                          style={{
                            background: tagItem.autoGenerated ? 'rgba(100, 116, 139, 0.14)' : 'rgba(31, 138, 112, 0.14)',
                            display: 'inline-flex',
                            alignItems: 'center',
                            gap: 6,
                          }}
                        >
                          {tagItem.tagText}
                          <button
                            onClick={() => void removeTag(tagItem)}
                            style={{
                              background: 'none',
                              border: 'none',
                              cursor: 'pointer',
                              color: 'inherit',
                              padding: 0,
                              fontSize: '1.1em',
                              lineHeight: 1,
                            }}
                          >
                            ×
                          </button>
                        </span>
                      ))}
                      {tags.length === 0 && <span style={{ fontSize: '0.85em', color: 'var(--ink-soft)' }}>No tags yet.</span>}
                    </div>
                  )}
                </div>
              </div>
            ) : (
              <div
                style={{
                  color: 'var(--ink-soft)',
                  padding: 16,
                  border: '1px dashed rgba(0, 0, 0, 0.2)',
                  borderRadius: 14,
                  textAlign: 'center',
                }}
              >
                No detail found for this picture.
              </div>
            )}
          </section>

          {/* Decision Panel */}
          <section className="panel soft">
            <h2 style={{ margin: '0 0 16px', fontSize: '1.1rem' }}>Decision</h2>
            <div style={{ display: 'grid', gap: 16 }}>
              <div style={{ display: 'grid', gap: 6 }}>
                <span style={{ fontSize: '0.9em', fontWeight: 500 }}>Status</span>
                <div style={{ display: 'flex', gap: 8 }}>
                  <Button
                    variant={reviewStatus === 'APPROVED' ? 'primary' : 'plain'}
                    onClick={() => setReviewStatus('APPROVED')}
                  >
                    Approve
                  </Button>
                  <Button
                    variant={reviewStatus === 'REJECTED' ? 'primary' : 'plain'}
                    onClick={() => setReviewStatus('REJECTED')}
                  >
                    Reject
                  </Button>
                </div>
              </div>
              <div style={{ display: 'grid', gap: 6 }}>
                <span style={{ fontSize: '0.9em', fontWeight: 500 }}>Reason (optional)</span>
                <Textarea
                  value={reviewReason}
                  onChange={(e) => setReviewReason(e.target.value)}
                  placeholder="Explain the decision"
                  rows={3}
                />
              </div>
              <Button variant="primary" onClick={() => void submitReview()} disabled={reviewing}>
                {reviewing ? 'Submitting...' : 'Submit Review'}
              </Button>
            </div>
          </section>
        </div>

        {/* Review History */}
        <section className="panel">
          <h2 style={{ margin: '0 0 16px', fontSize: '1.1rem' }}>Review History</h2>
          {loading ? (
            <div>Loading...</div>
          ) : history.length === 0 ? (
            <div style={{ color: 'var(--ink-soft)', padding: 16, textAlign: 'center' }}>No review history yet.</div>
          ) : (
            <div style={{ display: 'grid', gap: 12 }}>
              {history.map((item) => (
                <div
                  key={item.id}
                  style={{
                    padding: 12,
                    borderLeft: '3px solid var(--accent)',
                    background: 'rgba(0, 0, 0, 0.02)',
                    borderRadius: 8,
                  }}
                >
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline' }}>
                    <strong>{item.toStatus}</strong>
                    <span style={{ fontSize: '0.85em', color: 'var(--ink-soft)' }}>
                      {new Date(item.reviewedAt).toLocaleString()}
                    </span>
                  </div>
                  <div style={{ fontSize: '0.85em', color: 'var(--ink-soft)', marginTop: 4 }}>
                    {item.reviewerDisplayName || item.reviewerUsername || item.reviewerId}
                  </div>
                  {item.reason ? (
                    <div style={{ fontStyle: 'italic', color: 'var(--ink-soft)', marginTop: 6 }}>
                      "{item.reason}"
                    </div>
                  ) : null}
                </div>
              ))}
            </div>
          )}
        </section>
      </div>
    </PageShell>
  )
}

