<script setup lang="ts">
import { onMounted, reactive, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import { ElMessage } from 'element-plus'
import {
  addPictureTags,
  getAdminPicture,
  listPictureTags,
  listReviews,
  removePictureTag,
  reviewPicture,
  type AdminPictureSummary,
  type ModerationRecord,
  type PictureTag,
} from '@/api/pictures'
import { listTags } from '@/api/tags'
import { formatBytes, formatDate } from '@/utils/format'

type TagOption = { value: string }

const route = useRoute()
const pictureId = String(route.params.id)

const detail = ref<AdminPictureSummary | null>(null)
const history = ref<ModerationRecord[]>([])
const loading = ref(false)
const reviewing = ref(false)
const tags = ref<PictureTag[]>([])
const tagsLoading = ref(false)
const tagInput = ref('')
const addingTag = ref(false)
const selectedTagName = ref('')

const reviewForm = reactive({
  status: 'APPROVED' as 'APPROVED' | 'REJECTED',
  reason: '',
})

const loadDetail = async () => {
  const cached = sessionStorage.getItem('cpp:admin:selected')
  if (cached) {
    try {
      const parsed = JSON.parse(cached) as AdminPictureSummary
      if (parsed?.id === pictureId) {
        detail.value = parsed
      }
    } catch {
      detail.value = null
    }
  }
  try {
    detail.value = await getAdminPicture(pictureId)
  } catch {
    detail.value = detail.value || null
  }
}

const loadTags = async () => {
  tagsLoading.value = true
  try {
    tags.value = await listPictureTags(pictureId)
  } catch (error: any) {
    ElMessage.error(error?.response?.data?.message || 'Failed to load tags')
  } finally {
    tagsLoading.value = false
  }
}

const loadHistory = async () => {
  loading.value = true
  try {
    const data = await listReviews(pictureId, { page: 0, size: 20, sortBy: 'reviewedAt', sortDir: 'desc' })
    history.value = data.items
  } catch (error: any) {
    ElMessage.error(error?.response?.data?.message || 'Failed to load review history')
  } finally {
    loading.value = false
  }
}

const fetchTagSuggestions = async (queryString: string, cb: (items: TagOption[]) => void) => {
  const keyword = queryString.trim()
  if (!keyword) {
    cb([])
    return
  }
  try {
    const data = await listTags({ page: 0, size: 8, keyword })
    cb(data.items.map((item) => ({ value: item.name })))
  } catch {
    cb([])
  }
}

const handleTagSelect = (option: TagOption) => {
  tagInput.value = option.value
  selectedTagName.value = option.value
}

const addTag = async () => {
  const value = tagInput.value.trim()
  if (!value) {
    ElMessage.warning('Tag text is required')
    return
  }
  addingTag.value = true
  try {
    tags.value = await addPictureTags(pictureId, {
      tags: [{ text: value }],
      provider: 'manual',
      autoGenerated: false,
    })
    tagInput.value = ''
    selectedTagName.value = ''
  } catch (error: any) {
    ElMessage.error(error?.response?.data?.message || 'Failed to add tag')
  } finally {
    addingTag.value = false
  }
}

const removeTag = async (tag: PictureTag) => {
  try {
    await removePictureTag(pictureId, tag.id)
    tags.value = tags.value.filter((item) => item.id !== tag.id)
  } catch (error: any) {
    ElMessage.error(error?.response?.data?.message || 'Failed to remove tag')
  }
}

const submitReview = async () => {
  reviewing.value = true
  try {
    await reviewPicture(pictureId, {
      status: reviewForm.status,
      reason: reviewForm.reason || undefined,
    })
    ElMessage.success('Review submitted')
    reviewForm.reason = ''
    await loadHistory()
  } catch (error: any) {
    ElMessage.error(error?.response?.data?.message || 'Review failed')
  } finally {
    reviewing.value = false
  }
}

watch(tagInput, (value) => {
  if (!value || value !== selectedTagName.value) {
    selectedTagName.value = value
  }
})

onMounted(async () => {
  await loadDetail()
  await loadTags()
  await loadHistory()
})
</script>

<template>
  <div class="page">
    <div class="page-header">
      <div>
        <h1 class="page-title">Review Detail</h1>
        <p class="page-subtitle">Approve or reject with a clear reason.</p>
      </div>
    </div>

    <div class="grid cols-2">
      <section class="panel">
        <h2 class="panel-title">Asset</h2>
        <div v-if="detail" class="detail-card">
          <div class="detail-image">
            <img :src="detail.url" :alt="detail.name" />
          </div>
          <div class="detail-info">
            <h3>{{ detail.name }}</h3>
            <div class="detail-row">
              <span>Owner</span>
              <strong>{{ detail.ownerDisplayName || detail.ownerUsername || '--' }}</strong>
            </div>
            <div class="detail-row">
              <span>Size</span>
              <strong>{{ formatBytes(detail.sizeBytes) }}</strong>
            </div>
            <div class="detail-row">
              <span>Resolution</span>
              <strong>{{ detail.width || '--' }} x {{ detail.height || '--' }}</strong>
            </div>
          </div>
          <div class="detail-tags">
            <div class="tag-header">
              <strong>Tags</strong>
              <span class="meta">{{ tags.length }} total</span>
            </div>
            <div class="tag-editor">
              <el-autocomplete
                v-model="tagInput"
                placeholder="Add a tag"
                clearable
                :fetch-suggestions="fetchTagSuggestions"
                @select="handleTagSelect"
                @keyup.enter="addTag"
              />
              <el-button type="primary" plain :loading="addingTag" @click="addTag">Add</el-button>
            </div>
            <div v-if="tagsLoading" class="meta">Loading tags...</div>
            <div v-else class="tag-list">
              <el-tag
                v-for="tagItem in tags"
                :key="tagItem.id"
                closable
                :type="tagItem.autoGenerated ? 'info' : 'success'"
                @close="removeTag(tagItem)"
              >
                {{ tagItem.tagText }}
              </el-tag>
              <span v-if="tags.length === 0" class="meta">No tags yet.</span>
            </div>
          </div>
        </div>
        <div v-else class="detail-empty">No detail found for this picture.</div>
      </section>

      <section class="panel soft">
        <h2 class="panel-title">Decision</h2>
        <el-form label-position="top">
          <el-form-item label="Status">
            <el-radio-group v-model="reviewForm.status">
              <el-radio-button label="APPROVED">Approve</el-radio-button>
              <el-radio-button label="REJECTED">Reject</el-radio-button>
            </el-radio-group>
          </el-form-item>
          <el-form-item label="Reason (optional)">
            <el-input v-model="reviewForm.reason" type="textarea" rows="3" placeholder="Explain the decision" />
          </el-form-item>
          <el-button type="primary" :loading="reviewing" @click="submitReview">
            Submit Review
          </el-button>
        </el-form>
      </section>
    </div>

    <section class="panel">
      <h2 class="panel-title">Review History</h2>
      <el-skeleton v-if="loading" :rows="4" animated />
      <el-timeline v-else>
        <el-timeline-item
          v-for="item in history"
          :key="item.id"
          :timestamp="formatDate(item.reviewedAt)"
          placement="top"
        >
          <div class="history-card">
            <strong>{{ item.toStatus }}</strong>
            <div class="meta">
              {{ item.reviewerDisplayName || item.reviewerUsername || item.reviewerId }}
            </div>
            <div v-if="item.reason" class="reason">"{{ item.reason }}"</div>
          </div>
        </el-timeline-item>
      </el-timeline>
      <div v-if="!loading && history.length === 0" class="detail-empty">
        No review history yet.
      </div>
    </section>
  </div>
</template>

<style scoped>
.panel-title {
  margin: 0 0 16px;
  font-size: 1.1rem;
}

.detail-card {
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.detail-image {
  width: 100%;
  border-radius: 18px;
  overflow: hidden;
  aspect-ratio: 4 / 3;
  background: #efe7dd;
}

.detail-image img {
  width: 100%;
  height: 100%;
  object-fit: cover;
}

.detail-info h3 {
  margin: 0 0 12px;
}

.detail-row {
  display: flex;
  justify-content: space-between;
  color: var(--ink-soft);
  margin-bottom: 8px;
}

.detail-row strong {
  color: var(--ink-strong);
}

.detail-tags {
  display: grid;
  gap: 10px;
}

.tag-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.tag-editor {
  display: flex;
  gap: 10px;
  align-items: center;
  flex-wrap: wrap;
}

.tag-editor :deep(.el-autocomplete) {
  width: 220px;
}

.tag-list {
  display: flex;
  gap: 8px;
  flex-wrap: wrap;
}

.detail-empty {
  color: var(--ink-soft);
  padding: 16px;
  border: 1px dashed rgba(0, 0, 0, 0.2);
  border-radius: 14px;
  text-align: center;
}

.history-card {
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.reason {
  font-style: italic;
  color: var(--ink-soft);
}
</style>
