import api, { unwrap } from '@/api/client'
import type { ApiResponse, PageResponse } from '@/api/client'

export type PictureSummary = {
  id: string
  name: string
  url: string
  visibility: 'PUBLIC' | 'PRIVATE' | 'TEAM'
  sizeBytes: number
  width?: number | null
  height?: number | null
}

export type PictureResponse = PictureSummary & {
  reviewStatus: 'PENDING' | 'APPROVED' | 'REJECTED'
  contentType?: string | null
}

export type PictureDetailTag = {
  id: string
  pictureAssetId: string
  tagId?: string | null
  tagText: string
  confidenceScore?: number | null
  provider?: string | null
  autoGenerated?: boolean | null
  createdAt: string
}

export type PictureDetail = PictureResponse & {
  originalFilename?: string | null
  checksum?: string | null
  ownerId: string
  ownerUsername?: string | null
  ownerDisplayName?: string | null
  spaceId?: string | null
  spaceName?: string | null
  spaceType?: 'PERSONAL' | 'TEAM' | null
  teamId?: string | null
  teamName?: string | null
  createdAt: string
  updatedAt: string
  canEdit: boolean
  canManage: boolean
  canJoinCollaboration: boolean
  tags: PictureDetailTag[]
}

export type PictureDocumentElement = {
  id: string
  type: 'rect' | 'text'
  x: number
  y: number
  width: number
  height: number
  text?: string | null
}

export type PictureDocument = {
  pictureId: string
  schemaVersion: string
  version: number
  lastUpdatedByUserId?: string | null
  updatedAt?: string | null
  elements: PictureDocumentElement[]
}

export type RapidUploadCheckResponse = {
  exists: boolean
  existingPictureId?: string | null
  sizeBytes?: number | null
  url?: string | null
  width?: number | null
  height?: number | null
  message: string
}

export type EditorRealtimeEventDefinition = {
  eventType: string
  payloadType: string
  description: string
}

export type EditorRealtimeContract = {
  eventSchemaVersion: string
  documentMutationRequiresLock?: boolean
  documentVersionCheckSupported?: boolean
  lockTtlSeconds?: number
  websocketEndpoint: string
  topicDestination: string
  userQueueDestination: string
  joinDestination: string
  leaveDestination: string
  lockDestination: string
  lockRefreshDestination?: string
  unlockDestination: string
  eventDestination: string
  supportedEvents: string[]
  eventDefinitions: EditorRealtimeEventDefinition[]
}

export type PictureCollaborationRoom = {
  contractVersion: string
  provider: string
  roomId: string
  pictureId: string
  serverUrl: string
  token: string
  tokenExpiresAt: string
  permission: 'VIEWER' | 'EDITOR' | 'OWNER' | string
  awarenessEnabled: boolean
  indexedDbRecommended: boolean
  recommendedLibraries: string[]
}

export type PictureEditorSession = {
  pictureId: string
  sessionContractVersion: string
  document: PictureDocument
  presence: {
    pictureId: string
    users: Array<{
      userId: string
      username: string
      joinedAt: string
    }>
    lock?: {
      lockedByUserId: string
      lockedByUsername: string
      lockedAt: string
      expiresAt: string
    } | null
  }
  realtime: EditorRealtimeContract
  room: PictureCollaborationRoom
}

export type AdminPictureSummary = PictureSummary & {
  reviewStatus: 'PENDING' | 'APPROVED' | 'REJECTED'
  ownerId: string
  ownerUsername?: string | null
  ownerDisplayName?: string | null
  lastReviewerId?: string | null
  lastReviewerUsername?: string | null
  lastReviewerDisplayName?: string | null
  lastReviewedAt?: string | null
}

export type ModerationRecord = {
  id: string
  pictureId: string
  reviewerId: string
  reviewerUsername?: string | null
  reviewerDisplayName?: string | null
  fromStatus: 'PENDING' | 'APPROVED' | 'REJECTED'
  toStatus: 'PENDING' | 'APPROVED' | 'REJECTED'
  reason?: string | null
  reviewedAt: string
}

export async function listPublic(params: {
  page?: number
  size?: number
  keyword?: string
  minSizeBytes?: number
  maxSizeBytes?: number
  orientation?: 'LANDSCAPE' | 'PORTRAIT' | 'SQUARE'
}) {
  const response = await api.get<ApiResponse<PageResponse<PictureSummary>>>('/api/pictures/public', {
    params,
  })
  return unwrap(response.data)
}

export async function listRecommendations(params: { page?: number; size?: number }) {
  const response = await api.get<ApiResponse<PageResponse<PictureSummary>>>(
    '/api/pictures/recommendations',
    { params }
  )
  return unwrap(response.data)
}

export async function searchPictures(params: {
  page?: number
  size?: number
  keyword?: string
  ownerId?: string
  spaceId?: string
  visibility?: 'PUBLIC' | 'PRIVATE' | 'TEAM'
  reviewStatus?: 'PENDING' | 'APPROVED' | 'REJECTED'
  minSizeBytes?: number
  maxSizeBytes?: number
  createdAfter?: string
  createdBefore?: string
  orientation?: 'LANDSCAPE' | 'PORTRAIT' | 'SQUARE'
  tag?: string
  tagId?: string
  sortBy?: 'createdAt' | 'updatedAt' | 'sizeBytes'
  sortDir?: 'asc' | 'desc'
}) {
  const response = await api.get<ApiResponse<PageResponse<PictureSummary>>>('/api/pictures/search', {
    params,
  })
  return unwrap(response.data)
}

export async function uploadPicture(payload: {
  file: File
  visibility: 'PUBLIC' | 'PRIVATE' | 'TEAM'
  name?: string
  spaceId?: string
}) {
  const formData = new FormData()
  formData.append('file', payload.file)
  formData.append('visibility', payload.visibility)
  if (payload.name) formData.append('name', payload.name)
  if (payload.spaceId) formData.append('spaceId', payload.spaceId)
  const response = await api.post<ApiResponse<PictureResponse>>('/api/pictures/upload', formData)
  return unwrap(response.data)
}

export async function uploadPictureWithDeduplication(payload: {
  file: File
  visibility: 'PUBLIC' | 'PRIVATE' | 'TEAM'
  name?: string
  spaceId?: string
}) {
  const formData = new FormData()
  formData.append('file', payload.file)
  formData.append('visibility', payload.visibility)
  if (payload.name) formData.append('name', payload.name)
  if (payload.spaceId) formData.append('spaceId', payload.spaceId)
  const response = await api.post<ApiResponse<PictureResponse>>('/api/pictures/upload/deduplication', formData)
  return unwrap(response.data)
}

export async function checkDuplicatePicture(sha256Hash: string) {
  const response = await api.get<ApiResponse<RapidUploadCheckResponse>>('/api/pictures/check-duplicate', {
    params: { sha256Hash },
  })
  return unwrap(response.data)
}

export async function getPictureDetail(pictureId: string) {
  const response = await api.get<ApiResponse<PictureDetail>>(`/api/pictures/${pictureId}`)
  return unwrap(response.data)
}

export async function getPictureDocument(pictureId: string) {
  const response = await api.get<ApiResponse<PictureDocument>>(`/api/pictures/${pictureId}/document`)
  return unwrap(response.data)
}

export async function getPictureEditorSession(pictureId: string) {
  const response = await api.get<ApiResponse<PictureEditorSession>>(
    `/api/pictures/${pictureId}/editor-session`
  )
  return unwrap(response.data)
}

export async function getPictureCollaborationRoom(pictureId: string) {
  const response = await api.get<ApiResponse<PictureCollaborationRoom>>(
    `/api/pictures/${pictureId}/collaboration-room`
  )
  return unwrap(response.data)
}

export async function refreshPictureCollaborationRoom(pictureId: string) {
  const response = await api.post<ApiResponse<PictureCollaborationRoom>>(
    `/api/pictures/${pictureId}/collaboration-room/refresh`
  )
  return unwrap(response.data)
}

export async function listPending(page = 0, size = 20) {
  const response = await api.get<ApiResponse<PageResponse<AdminPictureSummary>>>(
    '/api/admin/pictures/pending',
    { params: { page, size } }
  )
  return unwrap(response.data)
}

export async function getAdminPicture(pictureId: string) {
  const response = await api.get<ApiResponse<AdminPictureSummary>>(`/api/admin/pictures/${pictureId}`)
  return unwrap(response.data)
}

export async function listReviews(
  pictureId: string,
  params: {
    page?: number
    size?: number
    reviewerId?: string
    fromStatus?: string
    toStatus?: string
    reviewedAfter?: string
    reviewedBefore?: string
    sortBy?: string
    sortDir?: string
  }
) {
  const response = await api.get<ApiResponse<PageResponse<ModerationRecord>>>(
    `/api/admin/pictures/${pictureId}/reviews`,
    { params }
  )
  return unwrap(response.data)
}

export async function reviewPicture(pictureId: string, payload: { status: 'APPROVED' | 'REJECTED'; reason?: string }) {
  const response = await api.post<ApiResponse<PictureResponse>>(
    `/api/admin/pictures/${pictureId}/review`,
    payload
  )
  return unwrap(response.data)
}

export type PictureTag = {
  id: string
  pictureAssetId: string
  tagId?: string | null
  tagText: string
  confidenceScore?: number | null
  provider?: string | null
  autoGenerated?: boolean | null
  createdAt: string
}

export async function listPictureTags(pictureId: string) {
  const response = await api.get<ApiResponse<PictureTag[]>>(`/api/pictures/${pictureId}/tags`)
  return unwrap(response.data)
}

export async function addPictureTags(
  pictureId: string,
  payload: {
    tags: { text: string; confidenceScore?: number }[]
    provider?: string
    autoGenerated?: boolean
  }
) {
  const response = await api.post<ApiResponse<PictureTag[]>>(`/api/pictures/${pictureId}/tags`, payload)
  return unwrap(response.data)
}

export async function removePictureTag(pictureId: string, tagId: string) {
  const response = await api.delete<ApiResponse<void>>(`/api/pictures/${pictureId}/tags/${tagId}`)
  return unwrap(response.data)
}

export async function exportReviews(params: {
  pictureId?: string
  reviewerId?: string
  fromStatus?: string
  toStatus?: string
  reviewedAfter?: string
  reviewedBefore?: string
  sortBy?: string
  sortDir?: string
  limit?: number
}) {
  const response = await api.get('/api/admin/pictures/reviews/export', {
    params,
    responseType: 'blob',
  })
  return response.data as Blob
}
