import api, { unwrap } from '@/api/client'
import type { ApiResponse, PageResponse } from '@/api/client'

export type PictureSummary = {
  id: string
  name: string
  url: string
  visibility: 'PUBLIC' | 'PRIVATE' | 'TEAM'
  sizeBytes: number
  width?: number | null
  height?: number | null
}

export type PictureResponse = PictureSummary & {
  reviewStatus: 'PENDING' | 'APPROVED' | 'REJECTED'
  contentType?: string | null
}

export type AdminPictureSummary = PictureSummary & {
  reviewStatus: 'PENDING' | 'APPROVED' | 'REJECTED'
  ownerId: string
  ownerUsername?: string | null
  ownerDisplayName?: string | null
  lastReviewerId?: string | null
  lastReviewerUsername?: string | null
  lastReviewerDisplayName?: string | null
  lastReviewedAt?: string | null
}

export type ModerationRecord = {
  id: string
  pictureId: string
  reviewerId: string
  reviewerUsername?: string | null
  reviewerDisplayName?: string | null
  fromStatus: 'PENDING' | 'APPROVED' | 'REJECTED'
  toStatus: 'PENDING' | 'APPROVED' | 'REJECTED'
  reason?: string | null
  reviewedAt: string
}

export async function listPublic(params: {
  page?: number
  size?: number
  keyword?: string
  minSizeBytes?: number
  maxSizeBytes?: number
  orientation?: 'LANDSCAPE' | 'PORTRAIT' | 'SQUARE'
}) {
  const response = await api.get<ApiResponse<PageResponse<PictureSummary>>>('/api/pictures/public', {
    params,
  })
  return unwrap(response.data)
}

export async function searchPictures(params: {
  page?: number
  size?: number
  keyword?: string
  ownerId?: string
  spaceId?: string
  visibility?: 'PUBLIC' | 'PRIVATE' | 'TEAM'
  reviewStatus?: 'PENDING' | 'APPROVED' | 'REJECTED'
  minSizeBytes?: number
  maxSizeBytes?: number
  createdAfter?: string
  createdBefore?: string
  orientation?: 'LANDSCAPE' | 'PORTRAIT' | 'SQUARE'
  tag?: string
  tagId?: string
  sortBy?: 'createdAt' | 'updatedAt' | 'sizeBytes'
  sortDir?: 'asc' | 'desc'
}) {
  const response = await api.get<ApiResponse<PageResponse<PictureSummary>>>('/api/pictures/search', {
    params,
  })
  return unwrap(response.data)
}

export async function uploadPicture(payload: {
  file: File
  visibility: 'PUBLIC' | 'PRIVATE'
  name?: string
}) {
  const formData = new FormData()
  formData.append('file', payload.file)
  formData.append('visibility', payload.visibility)
  if (payload.name) {
    formData.append('name', payload.name)
  }
  const response = await api.post<ApiResponse<PictureResponse>>('/api/pictures/upload', formData)
  return unwrap(response.data)
}

export async function listPending(page = 0, size = 20) {
  const response = await api.get<ApiResponse<PageResponse<AdminPictureSummary>>>(
    '/api/admin/pictures/pending',
    { params: { page, size } }
  )
  return unwrap(response.data)
}

export async function getAdminPicture(pictureId: string) {
  const response = await api.get<ApiResponse<AdminPictureSummary>>(`/api/admin/pictures/${pictureId}`)
  return unwrap(response.data)
}

export async function listReviews(
  pictureId: string,
  params: {
    page?: number
    size?: number
    reviewerId?: string
    fromStatus?: string
    toStatus?: string
    reviewedAfter?: string
    reviewedBefore?: string
    sortBy?: string
    sortDir?: string
  }
) {
  const response = await api.get<ApiResponse<PageResponse<ModerationRecord>>>(
    `/api/admin/pictures/${pictureId}/reviews`,
    { params }
  )
  return unwrap(response.data)
}

export async function reviewPicture(pictureId: string, payload: { status: 'APPROVED' | 'REJECTED'; reason?: string }) {
  const response = await api.post<ApiResponse<PictureResponse>>(
    `/api/admin/pictures/${pictureId}/review`,
    payload
  )
  return unwrap(response.data)
}

export type PictureTag = {
  id: string
  pictureAssetId: string
  tagId?: string | null
  tagText: string
  confidenceScore?: number | null
  provider?: string | null
  autoGenerated?: boolean | null
  createdAt: string
}

export async function listPictureTags(pictureId: string) {
  const response = await api.get<ApiResponse<PictureTag[]>>(`/api/pictures/${pictureId}/tags`)
  return unwrap(response.data)
}

export async function addPictureTags(
  pictureId: string,
  payload: {
    tags: { text: string; confidenceScore?: number }[]
    provider?: string
    autoGenerated?: boolean
  }
) {
  const response = await api.post<ApiResponse<PictureTag[]>>(`/api/pictures/${pictureId}/tags`, payload)
  return unwrap(response.data)
}

export async function removePictureTag(pictureId: string, tagId: string) {
  const response = await api.delete<ApiResponse<void>>(`/api/pictures/${pictureId}/tags/${tagId}`)
  return unwrap(response.data)
}

export async function exportReviews(params: {
  pictureId?: string
  reviewerId?: string
  fromStatus?: string
  toStatus?: string
  reviewedAfter?: string
  reviewedBefore?: string
  sortBy?: string
  sortDir?: string
  limit?: number
}) {
  const response = await api.get('/api/admin/pictures/reviews/export', {
    params,
    responseType: 'blob',
  })
  return response.data as Blob
}
